name: Testing

on:
  push:
    branches:
      - 'main'
      - 'npm/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm i
      - run: npm build
      - run: npm test
